### ISSUE TITLE
before_payment being overwriten in checkout_controller_decorator.rb

### ISSUE THREAD

**Issue by styrken** [solidusio-contrib/solidus_product_assembly#110]
I was having this crazy issue where `before_payment` was not being called. I needed it to be called to be able to support payment wallets.

With the help of Marc Busqué from the core team we discovered that this gem mutes `before_payment`.

https://github.com/solidusio-contrib/solidus_product_assembly/blob/807c27773bedd55f7f104dd2ece719ed979c1f56/app/decorators/controllers/solidus_product_assembly/spree/checkout_controller_decorator.rb#L6

This is really not good, `before_payment` is used in solidus checkout_controller to set important wallet stuff.

See https://github.com/solidusio/solidus/blob/b4ff5ce951654ff070878da6a4ca7fba4418f135/frontend/app/controllers/spree/checkout_controller.rb#L201

Mark found that it's because of an solidus issue by looking at the blame: https://github.com/solidusio-contrib/solidus_product_assembly/commit/b426b735c58090164dc7443d79967ef7222db05c The referenced PR (https://github.com/spree/spree/commit/2e9a4a8d404b40a72dd2f1b0574a7705d9a61f71) has been merged so we are not sure if this still an issue or not.

But anyhow, it's not good to mute `before_payment` so we must try and find a better solution.

Let me know your thoughts.

**Comment by gsmendoza** [comment]
This is being fixed in https://github.com/solidusio-contrib/solidus_product_assembly/pull/112.

**Comment by fthobe** [comment]
@tvdeyen can be closed.
