### ISSUE TITLE
Cannot select parts

### ISSUE THREAD

**Issue by nigelb135** [solidusio-contrib/solidus_product_assembly#18]
I have installed the extension and all looks OK ... the new Parts tab appears and the new checkbox 'Can be part' is added. However, in the Parts tab no parts are listed or found.

The trace shows...

```
Deface: 1 overrides found for 'spree/admin/products/_form'
Deface: 'product_assembly_admin_product_form_right' matched 1 times with '[data-hook='admin_product_form_right'], #admin_product_form_right[data-hook]'
Deface: [WARNING] No :original defined for 'product_assembly_admin_product_form_right', you should change its definition to include:
 :original => 'aa6b8f723ba63fd838a148836c91315904338281' 
```

I am new to solidus/spree so expect that I have missed something. Guidance would be greatly appreciated. Nigel

**Comment by Senjai** [comment]
When you create a product, are you able to add parts to it?

**Comment by nigelb135** [comment]
No I cannot. Even though I have parts available they are not included in the selection list.

**Comment by nigelb135** [comment]
OK I've now realised that the issue is not that the parts are not listed, but that there is no way to add parts to a product. The warning is, i think, indicating that the right hand element of the page is not being displayed - that is presumably where the page allows addition of parths.

**Comment by nigelb135** [comment]
Now I'm embarrassed! I have been searching for parts using the SKU, just discovered that the search only works on the Product Name. Sorry for any wasted of time my error caused.
