### ISSUE TITLE
Inventory Validation fail upon checkout, for the assembly product

### ISSUE THREAD

**Issue by flyfy1** [solidusio-contrib/solidus_product_assembly#3]
Issue Cause: 

[this method](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/stock/inventory_validator.rb) is called before creating the order. The detailed code:

```rb
class InventoryValidator < ActiveModel::Validator
  def validate(line_item)
    if line_item.inventory_units.count != line_item.quantity
      line_item.errors[:inventory] << Spree.t(
        :inventory_not_available,
        item: line_item.variant.name
      )
    end
  end
end
```
However, for the assembly product, `line_item.inventory_units` is the combination of its child_elements.. therefore different from `line_item.quantity`.

**Comment by Sinetheta** [comment]
Thanks @flyfy1, I can confirm that this is a problem. I guess that speedy feature spec I wrote clearly didn't go far enough through checkout 😉

**Comment by Sinetheta** [comment]
Fixed by https://github.com/solidusio-contrib/solidus_product_assembly/pull/5
