### ISSUE TITLE
Deface is required

### ISSUE THREAD

**Issue by kevinjbayer** [solidusio-contrib/solidus_product_assembly#37]
This looks very promising for a project I'm about to start. I just tested it on a local install real quick and at first, nothing was loading into my admin views from this gem. I finally realized that the Deface gem is required and had to add it to my Gemfile manually. I see it's there in this projects Gemfile, but I'm wondering why it wasn't added after running bundle and the generator. This was on Rails 5.2.2 and Ruby 2.5.1.

**Comment by TheCrawlingChaos** [comment]
I am guessing it's because they didn't put it in the gemspec.

**Comment by kennyadsl** [comment]
This is probably because you are not using any other plugin with Deface required, which is very uncommon. Anyway, I agree that if Deface is needed we should have it into the gemspec. Would you mind creating a PR for that?

**Comment by spaghetticode** [comment]
Closing after PR https://github.com/solidusio-contrib/solidus_product_assembly/pull/44
