### ISSUE TITLE
`method_missing': undefined method `add_routes' 

### ISSUE THREAD

**Issue by caseygipson** [solidusio-contrib/solidus_product_assembly#39]
When installing via rubygems source this error comes up

/usr/local/bundle/gems/railties-5.2.2/lib/rails/railtie.rb:192:in `method_missing': undefined method `add_routes' for Spree::Core::Engine:Class (NoMethodError)

According to this [issue,](https://github.com/solidusio/solidus/issues/1687) it should be routes.draw

This error does not appear in local dev when installing from a git source, however I'm having issues installing from a git source in production and would like to use a rubygems source

**Comment by kennyadsl** [comment]
For now this gem updaes are only available via github source. Did you get how to use gems from github in production as well?

**Comment by spaghetticode** [comment]
@caseygipson any update on your issue?

**Comment by spaghetticode** [comment]
In the README we suggest to use the version from github:
```
gem 'solidus_product_assembly', github: 'solidusio-contrib/solidus_product_assembly', branch: 'master'
```
I think for the moment that's the best way to install the gem. We are going to release a new version in the near future.
