### ISSUE TITLE
Unable to delete product bundles or components from an order

### ISSUE THREAD

**Issue by modded-nate** [solidusio-contrib/solidus_product_assembly#58]
There are no edit or delete options for the product bundle itself in the Shipments tab, but there are options for the individual components. When trying to delete a component an [error is generated](https://prnt.sc/p1rai2) that says "The resource you were looking for could not be found".

**Workaround:** I needed to ship the package, and then use the cancel items tab to mark the individual components as short shipped.

**Comment by spaghetticode** [comment]
@modded-nate not 100% sure if this applies to your situation, but you should be able to remove the product bundle (the assembly) from the `Cart` tab.
