### ISSUE TITLE
Returns on product kits can result in reimbursements not equal to the order total

### ISSUE THREAD

**Issue by modded-nate** [solidusio-contrib/solidus_product_assembly#61]
During the RMA/Return process, a kit's components prices seem to be calculated based on the order total. For instance, we had a product assembly made from a quantity of 2 for component A and a quantity of 20 for component B, and the assembly price is 159.99 (with sales tax applied at 6% for each for an order total of 169.59).

When creating an RMA,  the component with 2 pieces in the assembly are calculated at [$43.39 each](http://prntscr.com/p6z3xs) (x 2 = $86.78 x 1.06 = 91.9868) and the second is calculated at [$3.66 each](http://prntscr.com/p6z4i1) [ (x 20 = $73.20) x 1.06 = 77.592). I created separate RMA's for component A and component B (they have different stock locations). The RMA for Component A pre-tax is showing as $86.79 and Component B is showing $73.20 ([totaling $159.99](http://prntscr.com/p6z4o8) = the correct price for the product kit).

When I create the Customer Return for Component A's RMA the reimbursement on the return detail page shows as [$91.99](http://prntscr.com/p6z538) while from the return overview page it shows as [$92.00](http://prntscr.com/p6z58p), and the return detail page for Component B's shows the reimbursement amount as [$77.59](http://prntscr.com/p6z5e7) while the return overview page shows [$77.60](http://prntscr.com/p6z5ix) (return detail 91.99 + 77.59 = $169.58, return overview 92.00 + 77.60 = $169.60).

Finally, on the Payments tab, the refunds list $91.99 and $77.59 ([$169.58](http://prntscr.com/p6z605)) as the refund amounts.

**Comment by spaghetticode** [comment]
@modded-nate thank you for reporting this. 

There are already [some tests](https://github.com/solidusio-contrib/solidus_product_assembly/blob/master/spec/features/admin/return_items_spec.rb) in place for scenarios similar to yours, everything works as expected there, but for sure they're simpler (no sales tax there, and possibly there may be further simplifications). 

I think there may be some rounding issue somewhere, but given that the existing tests pass, and you don't always experience this issue, it's hard to determine what could be causing this specific problem. 

I think that the best way to approach this would be to investigate your specific case (ie. records in the database) and eventually the reason should become apparent, but I'm not sure how we could handle this... or you could provide a failing test that somebody will try to fix
